<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite errors="1" failures="0" hostname="fv-az442-293" name="pytest" skipped="0" tests="1" time="0.096" timestamp="2023-05-19T06:15:27.589772"><testcase classname="" name="app.tests.test_hipotenusa" time="0.000"><error message="collection failure">app/tests/test_hipotenusa.py:4: in &lt;module&gt;
    raise Exception("Erro!")
E   Exception: Erro!</error></testcase></testsuite></testsuites>